/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputGroup: typeof import('@arco-design/web-vue')['InputGroup']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ApplicationMenu: typeof import('./src/components/ApplicationMenu.vue')['default']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Card: typeof import('./src/components/Card.vue')['default']
    Dashboard: typeof import('./src/components/chat/Dashboard.vue')['default']
    Declaration: typeof import('./src/components/profile/Declaration.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Index: typeof import('./src/components/chat/FriendList/Index.vue')['default']
    ListItem: typeof import('./src/components/chat/FriendList/ListItem.vue')['default']
    MainUserCard: typeof import('./src/components/MainUserCard.vue')['default']
    MiniRecord: typeof import('./src/components/profile/MiniRecord.vue')['default']
    MiniRecordList: typeof import('./src/components/profile/MiniRecordList.vue')['default']
    OnlineStatus: typeof import('./src/components/OnlineStatus.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    UserSearchPane: typeof import('./src/components/chat/search-pane/UserSearchPane.vue')['default']
  }
}
